* Estimation of excess air coefficient on coal combustion processes via gauss model and artificial neural network[J].  2021.
[[cite:&Golgiyaz-et.al._2022]]
《基于高斯模型和人工神经网络的煤燃烧过程过量空气系数估算》
本文对CCD摄像机获得的火焰图像与过量空气系数（k）之间的关系进行建模。其中通过单变量和多变量高斯建模、颜色概率计算和高斯混合方法，计算了每片火焰图像的均匀性，并运用多层人工神经网络（ANN）用于特征的匹配。

   
* An ensemble deep learning model for exhaust emissions prediction of heavy oil-fired boiler combustion[J]. Fuel.
[[cite:&Zh-et.al._2022]]
《重油锅炉燃烧排放预测的集成深度学习模型》
本研究提出了一种新的集成深度学习模型对重油锅炉燃烧的废气排放（NOx和CO2）预测。其中建立了叠加去噪自动编码器来提取火焰图像的深层特征，采用人工神经网络、极限学习机、支持向量机和最小二乘支持向量机四种预测引擎对NOx和CO2排放进行初步预测，最后这些初步预测通过高斯过程回归以非线性方式进行组合，以实现排放的最终预测。

* Prediction of combustion state through a semi-supervised learning model and flame imaging[J]. Fuel, 2020.
[[cite:&Ha-et.al._2020]]
《基于半监督学习模型和火焰成像的燃烧状态预测》
本研究提出了一种结合去噪自动编码器（DAE）、生成对抗网络（GAN）和高斯过程分类器（GPC）的半监督学习模型对重油燃烧锅炉炉膛火焰图像的燃烧状态进行预测。DAE网络用于提取火焰图像的代表性特征，并通过GAN的对抗性学习机制训练网络。为了提高DAE网络的特征学习能力，引入了结构相似性（SSIM）度量作为一种新的损失函数。然后将提取的特征输入GPC，以预测可见和不可见的燃烧状态。

* Deep learning-based super-resolution images for synchronous measurement of temperature and deformation at elevated temperature[J].2021.
[[cite:&Tang-et.al._2021]]
《基于深度学习的超分辨率图像同步测量高温下的温度和变形》
本文将图像捕获和处理方法结合起来，以获得高分辨率图像以及相应的温度场和变形场。超分辨率重建采用超分辨率卷积神经网络（SRCNN）算法，变形场采用DIC方法计算，温度场采用改进的双色法同步获得。
* Evaluation of Deep Learning-Based Segmentation Methods for Industrial Burner Flames[J]. Energies, 2021, 14.
[[cite:&Grokopf-et.al._2021]]
《基于深度学习的工业燃烧器火焰分割方法评价》
在这项研究中，研究了一种基于垃圾焚烧厂实例图像数据的深度学习方法对工业燃烧器火焰进行实例分割的能力。并使用几个卷积神经网络评估了在具有挑战性的情况下的分割质量和鲁棒性，并证明了基于深度学习的方法能够产生令人满意的结果。
*  Monitoring combustion instabilities of stratified swirl flames by feature extractions of time-averaged flame images using deep learning method[J].
[[cite:&Zhou-et.al._2020]]
《利用深度学习方法提取平均时间火焰图像特征监测分层旋流火焰的燃烧不稳定性》
本文研究了基于时间平均火焰图像的深度学习方法在燃烧不稳定性监测中的应用。在北航轴向旋流燃烧器（独立分层）的基础上，设计了一个名为BIM（BASIS Image Monitor）的CNN（卷积神经网络），用于从火焰形状中提取特征，并提前确定火焰的热声状态。由BIM特征提取和可视化并通过类激活图（CAM）方法反映了火焰图像及其稳定性之间的潜在统计联系，并能准确地识别其稳定性和不稳定特征。
* A comprehensive investigation of LSTM-CNN deep learning model for fast detection of combustion instability[J]. Fuel, 303.
[[cite:&Lyu-et.al._2021]]
《用于快速检测燃烧不稳定性的LSTM-CNN深度学习模型的综合研究》
本文提出了一种利用高速火焰图像序列检测燃烧不稳定性的深度学习模型。该检测模型结合了卷积神经网络（CNN）和长短期记忆网络（LSTM）从高速图像中学习空间特征和时间相关性，然后输出燃烧不稳定性检测结果。

* Combustion Instability Monitoring through Deep-Learning-Based Classification of Sequential High-Speed Flame Images[J].
[[cite:&Choi-et.al._2020]]
《基于深度学习的连续高速分类火焰图像监测燃烧不稳定性》
本研究提出了一种基于高速火焰图像的深度学习模型来诊断燃气轮机的燃烧不稳定性。建立了两个不同的网络层，可以与任何现有主干网络相结合：（1）早期融合层，可以学习提取后续图像帧的功率谱密度，在特定条件下是时不变的。（2）后期融合层，将主干网络在不同时间步的输出结合起来，以预测当前燃烧状态。

* Flame Image Processing and Classification Using a Pre-Trained VGG16 Model in Combustion Diagnosis[J]. 
[[cite:&Omiotek-Kotyra_2021]]
《燃烧诊断中基于预训练VGG16模型的火焰图像处理与分类》
本文提出了一种将火焰图像处理与深度卷积神经网络（DCNN）相结合的方法，确保了对非期望燃烧状态的高精度识别。该方法基于火焰分割过程中伽马校正系数（G）的自适应选择。它使用经验确定的G系数和R图像分量平均强度之间的关系，使用预先训练的VGG16模型进行分类。
* A Flame Imaging-Based Online Deep Learning Model for Predicting NOₓ Emissions From an Oxy-Biomass Combustion Process.
[[cite:&Qin-et.al._2022]]
《基于火焰成像的在线深度学习模型用于预测生物质富氧燃烧过程中的NOx排放》
在这项研究中，基于深度学习和条件识别模型，提出了一个ODL（在线深度学习）模型，用于预测“可见”和“不可见”燃烧条件下生物质含氧燃烧过程中的NOx排放。ODL模型主要基于“看不见的”燃烧条件建立。

* 参考文献                                                           :ignore:
bibliographystyle:unsrt
bibliography:./papers.bib

