# http://www.sblunwen.com/proposal/19056.html
* 研究生毕业论文开题报告写法
所谓开题报告，也是有两个意思：“开题”与“报告”。开题是对自己选题的说明，而报告则是向导师、向学院汇报自己的准备情况与研究计划，请求批准。因此，开题报告中的主要内容即为选题目的、选题意义、选题背景、研究计划、研究目标、可行性与创新性、主要参考文献。

一、毕业论文的题目。题目是毕业论文中心思想的高度概括，要求：①准确、规范。要将研究的问题准确地概括出来，反映出研究的深度和广度，反映出研究的性质，反映出实验研究的基本要求——处理因素、受试对象及实验效应等。用词造句要科学、规范。②简洁。要用尽可能少的文字表达，一般不得超过20个汉字。

二、介绍选题目的、意义。即先说明为什么要选择这个研究课题，交代研究的价值。一般先谈现实需要——由存在的问题导出研究的实际意义，然后再谈理论及学术价值，要求具体、客观，且具有针对性，注重资料分析基础，注重时代、地区或单位发展的需要，切忌空洞无物的口号。

三、介绍选题背景、现状和发展趋势。即文献综述，主要说明国内外的研究情况，关于这个课题前人曾做过哪些方面的研究、解决了哪些问题、还存在什么问题等。所谓综述的“综”即综合，综合某一学科领域在一定时期内的研究概况;“述”更多的并不是叙述，而是评述与述评，即要有作者自己的独特见解。要注重分析研究，善于发现问题，突出选题在当前研究中的位置、优势及突破点。综述的对象，除观点外，还可以是材料与方法等。

四、介绍本人研究的初步方案，需要解决的问题和突破的难点，预期的结果等。即说明自己的主攻方向是什么，研究中主要根据什么理论、采用什么方法、取得什么成果等。 整个研究在时间及顺序上如何安排，怎样分阶段进行，对每一阶段的起止时间、相应的研究内容及成果均要有明确的规定，阶段之间不能间断，以保证研究进程的连续性。

五、说明选题的可行性和创新性。不仅对可能遇到的最主要的、最根本的关键性困难与问题要有准确、科学的估计和判断，并采取可行的解决方法和措施，而且要突出重点，突出所选课题与同类其他研究的不同之处。

六、列出主要参考文献。最后要列出所查阅的主要参考文献，一方面可以反映作者立论的真实依据，另一方面也是对原著者创造性劳动的尊重，篇数以各校的规定为准。
* Internet环境下遥操作机器人系统传输时延研究
# 这个开题报告可能与学校的模板不完全一致，但是内容比较规范，存在的小问题主要有：
# 1. 不建议在研究现状部分简单地对参考文献进行罗列，应该尽可能地整理出研究的脉络；
# 2. 没有在正文中引用参考文献；
# 3. 部分标点是半角的。

** 一、选题背景及其意义
遥操作就是远距离操作，是在远方人的行为动作远距离作用下，使事物产生运动变化。遥操作是一种基础技术，应用领域相当广泛，如机器人领域、航空航天领域、基础科学试验、核工程、海底与远洋作业等。遥操作技术使移动机器人到达艰险的环境，通过机器人完成特定的任务，从而可以使人远离艰险的工作环境。

基于Internet的遥操作机器人是指将机器人与Internet连接，使人们可以在任何地方通过浏览器访问机器人，实现对机器人的远程监视和控制。它以Internet 为构架，不仅降低了遥操作系统的成本，也使机器人为Internet上越来越多的人们所熟悉和共享。  其中，数据传输是遥操作机器人系统的一个非常重要的组成部分。从通信领域来说，分为无线和有线数据传输。随着Internet的出现及广泛应用，通过Internet进行数据传输，实现远距离遥控机器人越来越成为一个重要研究向。

基于Internet的遥操作机器人系统，一方面得益于网络传输的显著优势，网络资源廉价、普及范围广、所需硬件少；另一方面，Internet上数据流具有多样性，遥操作机器人系统必需的实时性特点所需要的高优先级必然不能达到。同时，Internet本身固有的特点，由于网络延时和负荷变化所具有的随机性、可变性和不可预测性引起了遥操作控制过程中的随机时延及延迟抖动，遥操作机器人系统的可控性、稳定性及透明度都受到负面影响。在力觉临场感遥操作系统网络传输中的不确定时延往往导致机器人控制信息反馈回遥操作端有一段时间滞后。该滞后与网络当时的性能紧密相关，如拥挤程度、途经路径的长短等等。如果遥操作人员不把网络延时考虑进去，对机器人的当前运动状态无法做出正确的判断，就无法发送正确的遥控命令，控制也将出现偏差，严重的甚至有危险。因此不确定时延是远程遥控机器人研究的技术难点之一。具有临场感效果的遥操作机器人系统应用于太空活动和深海探测等距离遥远的地方，但远地从机器人与本地操作者之间长达几秒到几十秒不等的通信时延却成为影响系统正常工作的突出问题。这不仅降低了系统的临场感效果，使操作者难以实时地、真实地感知远地环境的情况，而且造成了系统的不稳定，尤其是在从机器人与环境发生力的交互作用过程中。具体说来，问题的根源主要集中在网络时延和数据可靠性两大问题上。其中，数据可靠性又与网络时延有着密不可分的关系。

目前，对于遥操作机器人系统网络时延问题应对策略的研究主要集中在控制理论领域，如基于电路网络理论的无源控制法则、基于现代控制理论的控制算法和虚拟现实技术的模型修正法等。其共同的特点是把网络看作一个不可知(黑盒子)和不可控的对象，在控制领域寻找应对方法,以期消除网络时延对遥操作系统中信息、数据传输带来的负面影响。但是，科学地讲，网络时延虽然具有相当显著的不确定性，但它是一个可控、可预测的对象。因而，从网络体系及网络时延本身出发，从遥操作机器人系统与网络的互动需求出发，提出满足遥操作机器人系统需求的时延相关的网络优化和适应性方法，从而与控制领域的研究成果达成互补的效果。在保证系统稳定性的基础上,尽可能地提高系统透明度，满足期望的操作性，达到系统稳定性与透明度的动态平衡性, 即随着系统状态在稳定性和透明度之间找到一个合理的折中,使得系统在稳定的基础上尽可能提高操作性能。通过跨学科的努力，从根本上解决Internet环境下网络时延及时延抖动对遥操作机器人系统的影响和限制，缩短遥操作机器人系统理论与实用化的距离，为遥操作机器人技术提供更加广阔的应用空间。
** 二、国内外研究动态
在很长一段时间，关于遥操作机器人系统的网络时延问题集中在控制理论领域，早在60年代Ferrell就指出时间延迟的存在会使远程机器人工作不稳定。这种不稳定性可以从以下几个角度分析：  在古典控制论奈奎斯特稳定性分析中，将复平面上开环频率特性曲线不能包围-1点作为系统稳定的条件，并进一步从工程角度出发，要求一个系统不但要做到稳定，还应该有相当的稳定裕量才可使用。然而一个系统的参数的不确定性，控制模型的不合理的简化，却会使系统在某些情况下失稳，网络机器人控制中典型的就是延时的不确定性所带来的系统不稳定，所以对网络机器人控制问题的研究往往要考虑系统的稳定性和鲁棒性(Robustness)，即“是否稳定”和“稳定裕量”。

从能量角度分析，遥操作系统要想保持稳定，其输入能量必须大于输出能量，而通讯系统的存在会很容易的违反这一要求。

从负反馈角度分析：负反馈是实现控制的基本方法，但负反馈并不能保证系统的稳定性，设计不好的负反馈系统的被控制量也会出现震荡的情况，即不稳定。一个闭环系统如果其闭环增益大于一，其半个工作周期等于时间延迟值，则系统将处于正反馈而非负反馈，此频率的能量将连续加入系统而导致系统的不稳定。

现阶段，遥操作机器人系统克服时延影响的研究发展策略主要集中在基于电路网络理论的无源控制法、基于现代控制理论的控制算法、基于虚拟现实技术的控制结构和控制算法等几个方面。

1989年，Raju S.首先提出用二端口网络理论分析遥操作系统的方法, 将遥操作系统与电路网络进行类比，并且通过分析指出影响系统不稳定性的原因在于通信时延造成了传输线的有源性，使人们认识到使有通信时延的遥控作业系统稳定是可能的，关键是控制远地和本地之间的通信环节，使其具有无源传输线的性能。

加拿大多伦多大学的Strassberg Y. 和Goldenberg A. A. 等人则利用现代控制理论中的Lyapunov稳定性判据分析临场感系统的稳定性条件。Lawrence D. A. 针对稳定性和临场感特性在时延下的不协调，提出了“无源距离( passivity distance)”和“透明距离( transparency distance)”的概念，用以指导临场感系统的设计。 Leung G. M. H. 和Francis B. A. 等人利用基于“无源距离”和“透明距离”的综合评价法设计临场感系统的结构, 并利用H∞最优控制理论指导时延下临场感系统中控制器的设计。

1984年,Noyes G. 和Sheridan T. B. 设计了用于遥操作的第一个视觉预测显示系统。在该系统中用机械手的计算机仿真模型叠加在经时延后反馈的机械手视频图象上，仿真模型和操作者之间是实时交互，用以预测远处环境中机械手的运动。实验证明，该方法可以极大地提高系统的操作性能。1986 年，Sheridan T. B. 又构造了实验系统用以验证视频预测显示的有效性。结果表明，在视频预测显示的帮助下，任务完成时间减少50%。

1992 年， Kototu T.等人基于Bejczy A. K. 在1990 年提出的“幻影机器人”的思想上，给虚拟从手加入了力反馈。结果表明，增加了力反馈使得控制稳定，而且从手的运动比仅靠图形显示判断接触力时快了三倍。

1996 年，Morikawa H. 等人通过建立“虚拟引导模型”引入预测力反馈。2000 年，Itoh T. 等人对基于半自动任务导向虚拟工具，并具有运动和力标定的人- 机协作遥操作系统提出了新的控制算法。

实际上，从研究人员对遥操作系统中得网络时延问题的探索研究过程中我们不难发现：基于电路网络理论的无源通讯法则所实现的控制算法对解决短时延问题具有较好的效果，而在长时延的情况下，要实现在保证系统稳定的同时又具有良好的可操作性则显得无能为力；由于现代控制理论的不完善及其系统实现上的困难等原因，基于现代控制理论所提出的各种控制算法亦未能较好地解决系统通信时延问题。然而，将虚拟现实技术用于临场感遥操作机器人系统来克服通信时延，从而确保系统的稳定性和可操作性得以同时实现。因此，我们认为虚拟现实技术必定会成为克服时延对遥操作系统产生的负面影响的研究的主流方向。

以上这些方法策略的共同点是：把网络看作一个不可知(黑盒子)和不可控的对象，在控制领域寻找应对网络时延的方法。而在Internet环境下的遥操作领域针对时延的网络通信相关方面的研究则不是太多。

基于Internet的遥操作机器人系统网络时延的研究主要是在定常时延和时变时延两个假设基础之上进行的。其中，以定常时延为基础的研究最为广泛而以时变时延为基础的研究更具有实用价值。现阶段的针对网络时延的研究大体可以分为以下几个方向：
1. 分析、研究时延特点，给出时延估测模型，并以此模型为基础研究整个遥操作机器人系统的控制模型；
2. 大量实验测试，分析时延呈现出来的统计特性，预测其可能遵循的函数规律；
3. 利用时延缓冲器管理算法，将时变时延转化为定常时延；
4. 通过修改、创新时钟同步算法，来获取较准确地单向传输时延；
5. 重点分析与评估传输时延对通过不同的传输协议传递信息所带来的负面影响，通过改进TCP/RTP/RTCP/UDP等网络协议来解决问题。
** 三、课题研究内容
通过目前遥操作机器人系统的发展现状可以发现，对于一般的遥操作机器人系统，带宽虽然有限，但通常还是能够得到保证，所以时延也几乎是常数。而基于Internet的遥操作机器人系统则有所不同，其传输时延则是不断变化的。遥操作机器人系统是时延敏感的，且实时性要求很高，因而Internet提供的这些通信条件给遥操作系统的开发带来很大困难，传输中的大时延、时延抖动和不能保证的带宽将引发不稳定的问题，如果不适当地进行控制就会导致系统性能极大下降。

基于上述问题，本文着重从网络时延进行研究，大致可以分为以下几个方面：
1. 基于时钟同步的网络单向时延的研究。研究时延问题的关键之一在于能比较精确地确定时延的大小，分析当前网络单向时延研究成果及相关方法，分析单向时延的统计特性，重点分析网络单向时延的特点及其对网络数据传输的特殊性；从其特性出发，建立基于时钟同步算法的单向时延测算算法模型，验证基于时钟同步算法的单向时延测算算法的有效性。
2. 对TCP协议进行改进。分析数据传输协议实现过程以及TCP协议内在三大机制：超时重传、慢启动和拥塞避让。在此基础上，总结开发新型数据传输协议需要达到的要点；基于上述模拟实验的有效结果及对协议的功能需求，在NS2中对TCP协议进行改进，通过引入时延变量以及以神经网络为基础的时延的智能预测模块重新构造TCP协议中拥塞控制机制，以期达到时延抖动小、连续有序和数据可靠传输的目的。
3. 在NS2网络模拟环境下，使用改进的TCP协议，分析具体数据传输场景，针对遥操作机器人系统的数据传输特点，模拟其数据包发送状况，通过改进的TCP协议进行数据报发送并跟踪，分析实验结果，验证改进后协议的有效性。
** 四、研究方案及难点
在基于Internet的机器人遥操作系统中，时延的一个显著的特点是变化。由于Internet 中数据传输时延是影响遥操作控制系统品质的一个主要因素，时延模型的建立是一切分析解决遥操作时延控制问题的基础，且时延(往往是随机时延)是由网络数据传输时带宽限制和网站上数据拥挤造成的。目前基于网络的遥操作系统已有的一些研究，大多建立在对网络时延的假设基础之上，由于网络时延的随机性和不可预测性,通过实验测试时延来研究网络控制系统更具有实际意义。

首先，我们应该分析当前网络时延的研究成果及相关方法，通过进行实验得到相关数据分析时延的特点和统计特性以及时延和时延抖动对遥操作系统的透明性和可操作性产生的负面影响，寻求二者之间可能存在的平衡关系。

其次，研究时延问题的关键之一在于能比较精确地确定时延的大小，因此需要设计新的时钟同步算法，使其同步的精度达到可以接受的程度，对单向时延进行更加精确地测算。进而建立基于时钟同步算法的单向时延测算算法模型，基于该模型建立实验拓扑结构，模拟数据传输场景，验证基于时钟同步算法的单向时延测算算法的有效性。

再次，利用更加精确地网络时延数据对TCP中的拥塞控制机制进行改进，对改进后的协议进行性能评估。通过在拥塞控制算法中加入时延变量，建立更适应于遥操作机器人系统实时性的改进的TCP传输协议，使得拥塞控制算法和时延的关系更加密切，让时延的变化能更快的反应到网络中数据的传输中去。

然后，可以将以神经网络为基础的时延的智能预测模块加入到改进的TCP协议，使其拥有对时延的一般的预测功能，辅助新的拥塞控制算法，以期达到更高的应用价值。

最后，在NS2网络模拟环境下，使用改进后的传输协议，建立网络拓扑图，模拟遥操作机器人系统的数据传输过程，验证新型协议的有效性；在实际环境中使用改进后的传输协议作为系统底层数据传输协议，从实用系统角度验证协议的有效性。
** 五、预期成果和可能的创新点
在对时延在网络数据传输中的特性分析、总结的基础上，通过设计新的时间同步算法，得到更加精确地网络时延，以此来改进TCP协议中现有的拥塞控制机制，并加入时延的智能预测模块，以期得到更加适合网络实时控制系统的数据传输协议，实现时延抖动小、连续有序和可靠地数据传输。

其中，可能的创新点有：一种新的时间同步算法，能更加精确地测量网络时延；增加了时延变量的拥塞控制机制，可以更快的将时延的变化反映到到数据的传输过程中；一个融入到改进后的传输协议的基于神经网络的时延智能预测模块，可以提高其实用性和稳定性。
** 六、论文工作计划
论文工作的总体时间安排：
1. 2015年9月，开题准备工作，查找基于Internet的遥操作机器人系统传输时延的相关资料，了解国内外的发展动态，对课题进行可行性分析，确定课题的最终研究方向及课题内容。
2. 2015年10月—2016年12月，进行深入分析，认真学习与本研究课题相关的理论知识。
3. 2016年1月—2016年2月，进行相关系统的概要设计和实验环境的搭建。
4. 2016年3月—2016年10月, 完成对相关算法的改进，并进行试验，验证有效性。
5. 2016年10月—2016年12月，总结和整理相关资料，进行论文的撰写，准备答辩。
** 七、主要参考文献
（略）