* D  Adams,  D  Oh,  D  Kim, et al. Prediction of SOx–NOx emission from a coal-fired CFB power plant with machine learning: Plant data learned by deep neural network and least square support vector machine[J]. Journal of Cleaner Production, 2020:122310.
 cite:&Adams-et.al._2020 
** 问题
1. 本文主要问题为研究不同的煤和石灰石性质对SOx、NOx排放预测精度的影响，这在以前的文献研究中常被假定为常数；
2. 在考虑不同的煤和石灰石性质的情况下，探索不同的特色技术，以最大限度地减少计算时间，并提高工业实施过程的模型精度。
** 方法
研究对象:循环流化床燃煤锅炉。

数据处理:从2019年9月27日至2019年5月3日收集的数据中，以1分钟的扫描速度，选择了25064个实例和380个特征(包括SOx和NOx)进行研究。在此期间，该电厂的装机容量范围为217~515 MW。由于实际操作中不可避免的电磁干扰、传感器故障等技术故障等原因，总会存在误测值。因此，本研究采用数据过滤技术将380个特征减少到包括SOx和NOx在内的30个特征。清除所有离群值和不一致数值的数据后，仍保留28个输入要素和2个输出要素的24,000个实例。为了研究煤和石灰岩性质对模型性能的影响，形成了两个数据集：一个没有煤和石灰岩性质(DaW)，另一个有性质(DaP)。由于开发的模型用于实际电厂实施，因此创建这两个数据集与了解文献中假设的成本相关。因此，DaP和DaW分别由（28和13）个输入特性和2个输出（SOx、NOx）组成。同时，准备好的数据被分成三个集合，即训练集(准备数据的80%)、验证集(训练集的10%)和测试集(准备数据的20%)。

文中对DaW和DaP这两个数据集都采用了深度神经网络（DNN）和最小二乘支持向量机(LSSVM)来进行输出预测。根据操作经验，通过成对关联和互动功能创建了DaP的另外三个版本，即通过特征之间的成对相关来过滤DaP，形成数据集DaPF;其次，基于专家领域知识在DaP中添加新的特征，形成DaPE；最后，对DaPE进行过滤，形成DaPEF。

最后使用每个数据实例的均方根误差(RMSE)和平均绝对误差(MAE)来量化模型在训练期间的性能。
** 讨论
结果表明，计入不同的煤和石灰石性质显著提高了SOx、NOx排放量的预测精度。对于NOx排放，DNN模型对于训练(测试)数据的MRE精度提高了39.24(41.72)%，而对于SOx排放，精度提高了26.58(11.04)%，而没有煤和石灰岩特性的情况下，DNN模型的精度提高了39.24(41.72)% 。LSSVM模型也证实了这些发现，其训练（测试）数据预测精度也分别提高了（74.01（71.45））和（26.51（16.57））%。在DaP的基础上所提出的三种特色技术，DNN和LSSVM在NOx排放情况下，综合考虑预测性能时，可以认为DaPF方法是总体性能最好的数据集，预测精度较高，计算花费也较少。然而，对于SOx排放来说，综合考虑预测性能时,可以认为DaPF方法是总体性能最好的数据集，但还需进一步研究才能确定。所以所建立的模型不仅可用于燃煤循环流化床锅炉的在线运行和优化，而且可用于低计算成本的电力生产放大。
** 结论
根据文献的研究结果可以发现，计入不同的煤和石灰石性质所建立的模型，能够显著提高SOx、NOx排放量的预测精度。同时根据该模型的数据集DaP所扩展来的三种特色技术也都能提高预测性能，尤其是DaPF方法，可以认为DaPF方法是总体性能最好的。

