* @article{CUI2021,
title = {Coupled simulation and deep-learning prediction of combustion and heat transfer processes in supercritical CO2 CFB boiler},
journal = {Advanced Powder Technology},
year = {2021},
issn = {0921-8831},
doi = {https://doi.org/10.1016/j.apt.2021.11.013},
url = {https://www.sciencedirect.com/science/article/pii/S0921883121005367},
author = {Ying Cui and Wenqi Zhong and Zongyan Zhou and Aibing Yu and Xuejiao Liu and Jun Xiang},
keywords = {Circulating fluidized bed, Coupled simulation, Supercritical CO, Deep-learning prediction}
** 问题
1. 如何更准确地观察超临界CO2(S-CO2)循环流化床锅炉(CFB)内的传热和燃煤特性。
2. 寻找一种能预测锅炉冷壁受热面温度分布的方法。
** 方法
将炉膛燃烧的三维流体力学模拟与传热管内工质传热的一维模型相结合，可以实现燃烧与传热过程的耦合。CFD方法和多项式拟合计算模型相结合，可以更准确地描述燃烧和传热过程，从而进行循环流化床锅炉的耦合仿真。耦合仿真方法可以在一定程度上实现循环流化床锅炉的燃烧优化。利用CFD数值模拟得到的数据对RBF模型进行训练，为了提高预测的准确性和数据的可靠性，RBF预测综合考虑了固定参数和变化参数，其中固定参数为受热面面积（A），变化参数为炉膛温度（Tw）、炉膛压降（P）、烟气流速（U），热通量（Q）。本研究共计算了10组CFD模拟条件。每组模拟条件包含300个热流变量，代表受热面上不同位置的一维热流分布。并分析比较两种方法下的壁面换热管的温度以及壁面温度场。
** 结论
对RBF预测和耦合模拟得到的螺旋壁加热器的管壁温度进行了比较，结果表明，在大多数情况下，最大偏差可以控制在8%以内，平均偏差为3.8%，结果吻合较好。将RBF神经网络预测得到的炉壁温度场与耦合仿真结果进行了比较，炉膛外环前壁温度场的预测结果与模拟值相吻合，最大偏差为5.6%，平均偏差为2.3%。外环左壁、内环前壁和内环左壁的温度场比较，预测值也与模拟值吻合较好。模拟炉壁温度与预测值之间的最大偏差和平均偏差（分别为6.2%和3.1%），进一步验证了RBF神经网络良好的预测能力。表明基于RBF神经网络对耦合模拟的预测，能得到较准确的炉壁和换热管温度分布，为大型工业超临界二氧化碳CFB锅炉的耦合仿真提供了一种更有效、更准确的方法。
** 今天的两个问题
 1. 耦合的好处
   CFD方法和多项式拟合计算模型相结合，可以更准确地描述燃烧和传热过程，得到了更精确的管外表面温度分布， 耦合仿真方法还在一定程度上实现循环流化床锅炉的燃烧优化。
 2. RBF的输出
    RBF的输出是根据10组CFD模拟条件，每组模拟条件包含300个热流变量的数据训练训练出来的，是连续的多数据的输出。其中做管壁温度对比选取的每根管子21个测点只是为了对比两种方法下的拟合情况选取的观测点，做对应点的比较。
    
    
* @article{0Numerical,
  title={Numerical study of the combustion and application of SNCR for NOx reduction in a lab-scale biomass boiler - ScienceDirect},
  author={ Mousavi, S. M.  and  Fatehi, H.  and  Bai, X. S. },
  journal={Fuel},
  volume={293},
}
** 问题
1. 解决如何减少生物质锅炉NOx排放的问题
2. 研究选择性非催化还原(SNCR)技术在生物质锅炉上减少氮氧化物排放的应用。
** 方法
以两种不同NOx生成的化学机理分别构建两种不同的机理模型，再将两种不同的还原机理结合起来，形成了一种能够模拟焦油物种详细反应的新机理。利用详细的反应机理对NOx排放进行了模拟，并对不同的NOx生成途径进行了研究。
** 结论
1. 焦油是生物质热解的主要产物之一，为了在模拟中考虑焦油的影响，需要一个精确的模型。
2. 燃料中的氮以NH3和HCN的形式进入锅炉，是生物质锅炉NO 排放的主要来源。
3. 在较高的高度低喷射氨的效果较差，如果在较低的高度喷射，可能会导致更高的NO排放。该锅炉的最佳喷氨高度为0.4m，炉膛内烟气温度在1150K   左右。
4. 通过增加喷氨量和NSR（氮的化学计量摩尔比）值，出口处可获得较低数量的NO 。
* D  Adams,  D  Oh,  D  Kim, et al. Prediction of SOx–NOx emission from a coal-fired CFB power plant with machine learning: Plant data learned by deep neural network and least square support vector machine[J]. Journal of Cleaner Production, 2020:122310.
[[cite:&Adams-et.al._2020]]
** 问题
1. 本文主要问题为研究不同的煤和石灰石性质对SOx、NOx排放预测精度的影响，这在以前的文献研究中常被假定为常数；
2. 在考虑不同的煤和石灰石性质的情况下，探索不同的特色技术，以最大限度地减少计算时间，并提高工业实施过程的模型精度。
** 方法
研究对象:循环流化床燃煤锅炉。

数据处理:从2019年9月27日至2019年5月3日收集的数据中，以1分钟的扫描速度，选择了25064个实例和380个特征(包括SOx和NOx)进行研究。在此期间，该电厂的装机容量范围为217~515 MW。由于实际操作中不可避免的电磁干扰、传感器故障等技术故障等原因，总会存在误测值。因此，本研究采用数据过滤技术将380个特征减少到包括SOx和NOx在内的30个特征。清除所有离群值和不一致数值的数据后，仍保留28个输入要素和2个输出要素的24,000个实例。为了研究煤和石灰岩性质对模型性能的影响，形成了两个数据集：一个没有煤和石灰岩性质(DaW)，另一个有性质(DaP)。由于开发的模型用于实际电厂实施，因此创建这两个数据集与了解文献中假设的成本相关。因此，DaP和DaW分别由（28和13）个输入特性和2个输出（SOx、NOx）组成。同时，准备好的数据被分成三个集合，即训练集(准备数据的80%)、验证集(训练集的10%)和测试集(准备数据的20%)。

文中对DaW和DaP这两个数据集都采用了深度神经网络（DNN）和最小二乘支持向量机(LSSVM)来进行输出预测。根据操作经验，通过成对关联和互动功能创建了DaP的另外三个版本，即通过特征之间的成对相关来过滤DaP，形成数据集DaPF;其次，基于专家领域知识在DaP中添加新的特征，形成DaPE；最后，对DaPE进行过滤，形成DaPEF。

最后使用每个数据实例的均方根误差(RMSE)和平均绝对误差(MAE)来量化模型在训练期间的性能。
** 讨论
结果表明，计入不同的煤和石灰石性质显著提高了SOx、NOx排放量的预测精度。对于NOx排放，DNN模型对于训练(测试)数据的MRE精度提高了39.24(41.72)%，而对于SOx排放，精度提高了26.58(11.04)%，而没有煤和石灰岩特性的情况下，DNN模型的精度提高了39.24(41.72)% 。LSSVM模型也证实了这些发现，其训练（测试）数据预测精度也分别提高了（74.01（71.45））和（26.51（16.57））%。在DaP的基础上所提出的三种特色技术，DNN和LSSVM在NOx排放情况下，综合考虑预测性能时，可以认为DaPF方法是总体性能最好的数据集，预测精度较高，计算花费也较少。然而，对于SOx排放来说，综合考虑预测性能时,可以认为DaPF方法是总体性能最好的数据集，但还需进一步研究才能确定。所以所建立的模型不仅可用于燃煤循环流化床锅炉的在线运行和优化，而且可用于低计算成本的电力生产放大。
** 结论
根据文献的研究结果可以发现，计入不同的煤和石灰石性质所建立的模型，能够显著提高SOx、NOx排放量的预测精度。同时根据该模型的数据集DaP所扩展来的三种特色技术也都能提高预测性能，尤其是DaPF方法，可以认为DaPF方法是总体性能最好的。


*  Zh A , Jian L A , Mmh B , et al. An ensemble deep learning model for exhaust emissions prediction of heavy oil-fired boiler combustion[J]. Fuel{0An,
[[cite:&Zh-et.al._2022]]
** 问题
1. 解决通过CFD分析来实现NOx和COx排放预测仿真分析复杂，计算量大，仿真方法很难实现在线测量的问题，采用数据驱动的方法不需要精确的方程，使用起来更加方便，而且性能可能更优越；
2. 提出了一种用于废气排放预测的集成深度学习模型，以实现对NOx和COx的排放预测，看是否能达到更好的预测性能。
** 方法
研究对象:4.2 MW重油锅炉。

数据处理:为了提取火焰图像的鲁棒特征，建立了堆叠式去噪自动编码器(SDAE),从火焰图像中提取具有代表性的特征，并将提取的图像特征被馈送到四个预测引擎（即ANN、ELM、SVM和LSSVM），以实现对排放的初步预测。最后运用高斯过程回归（GPR）将初始预测以非线性的方式结合起来，实现终点预测和置信区间估计。在实验中，重油锅炉在20%、40%和60%三种不同的燃料负荷（FLs）下运行，在每个FL下，根据不同的一次空气和二次空气创建五种燃烧条件从15种不同燃烧条件获得的火焰图像数据集，并对于每个燃烧条件，收集1000个RGB火焰图像；对完整数据集（15000张火焰图像），随机选择3000张图像（即200张图像/条件）并手动标记，而剩余的12000张图像保持未标记状态。这些未标记的图像用于特征提取网络SDAE的无监督训练（在训练数据集即12,000幅未标记图像中添加了损失率为0.2(φ=0.2)的高斯噪声）。标记图像用于特征分析模型的有监督训练，并将标记图像进一步分为三个数据集，分别用于训练（60%）、验证（20%）和测试（20%）排放预测模型。
** 讨论
1. 集成学习模型的预测精度R2随着损失率的增加呈现出先增加后降低的趋势。当φ=0.2时，预测精度最高，即NOx预测精度为0.96(验证数据集)和 0.97(测试数据集)，CO2预测精度为0.96(验证数据集)和0.96(测试数据集)。上述结果表明，适当的损失率可以有效地提高SDAE的特征学习能力，但过多的噪声干扰会严重降低数据质量，最终导致预测性能不佳。因此，为了确保集成学习模型的高精度性能和强鲁棒性，将损失率设置为0.2。
2. 基于SDAE特征的模型提供了最好的预测性能，并在第150次迭代时达到最大值，还降低了计算负担，即SDAE训练需要94.13min(即第150次迭代)。
3. 与单独的预测引擎相比，集成学习模型提供了更好的预测精度，RMSE和MAE最低，R2最高。对于NOx排放预测(如表6所示)，可以看到：(1)对于验证数据集，RMSE、MAE和R2分别达到6.79 \(mg/m^{3}\)、5.07 mg/m3和0.96；(2)对于测试数据集，RMSE、MAE和R2分别达到5.96 mg/m3、4.71 mg/m3和0.97。对于CO2排放预测(如表7所示)，可以看出：(1)对于验证数据集，RMSE、MAE和R2分别达到0.51%、0.34%和0.96%；(2)对于测试数据集，RMSE、MAE和R2达到0.45%, 0.33% and 0.96。
** 结论
主要结论如下：
1. 所建立的SDAE能够准确提取火焰图像的代表性特征，其训练效率和预测精度均有明显提高，优于PCA、EF、SAE和CDAE等其他网络；
2. 通过比较不同的预测引擎，无论预测NOx或CO2排放，集成学习模型的均方根误差和最大均方根误差最低，而R2最高。其中，NOx和CO2排放量的预测精度分别达到R2=0.97和R2=0.96；
3. 集合学习模型对NOx和CO2排放的预测时间分别为38.78ms/f和38.76ms/f。集成学习模型所消耗的预测时间虽然略高于单一预测引擎，但仍能满足实时监测的要求；
4. 集成学习模型除了点预测外，还可以生成置信区间，定量表征预测的不确定性。在实际检验中，将实际观测值覆盖在置信区间内，验证了预测模型的可靠性。该预测方法为燃烧过程中NOx和CO2排放的监测提供了一种很有前途的工具，未来的工作将加强预测模型的实际应用，如煤燃烧和生物质混烧燃烧。





* 参考文献                                                           :ignore:
bibliographystyle:unsrt
bibliography:./paper.bib

